Added scroll back to top button
anomic30/Storz pull request #59
Opened 2022-10-04 07:25 UTC by zugzwang03

# Description
I added a scroll back to top button to scroll back to the landing page immediately on click.
An extra dependency added is react-icons, for the uparrow material icon.
Formatting has been changed in the process in some files as I was using a formatter in my code editor.

Fixes #37 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-04 08:00 UTC, Sneakad requested changes
Please maintain the indentation in the headers and keep it in one line.

2022-10-04 08:04 UTC, Sneakad requested changes
There is no need to create a separate page/ component for the scroll-up button.

2022-10-04 09:06 UTC, zugzwang03 commented
is it fine now? @Sneakad

2022-10-05 14:37 UTC, zugzwang03 commented
@Sneakad @anomic30

2022-10-06 09:36 UTC, Sneakad commented
@zugzwang03 the scroll back to the top button is not appearing on the landing page. Can you show your UI?

2022-10-06 09:41 UTC, zugzwang03 commented
While I am trying to run your code in my local machine, the website is not working, it is asking for some magic API key, and I can't get it. I kind of guess worked, that the scroll button will work like this if I put on that code. I have no knowledge of API s yet :(

2022-10-06 10:18 UTC, zugzwang03 commented
> @zugzwang03, you can get the API keys by reading the [client/readme.md](https://github.com/anomic30/Storz/blob/main/client/README.md) file.

okayy

2022-10-06 17:43 UTC, zugzwang03 commented
yupp, done.
It was a z-index problem actually 
![scrolltop](https://user-images.githubusercontent.com/95460021/194382371-fff5c2be-c459-483f-9ba7-ce370044d052.png)

2022-10-06 17:44 UTC, zugzwang03 commented
Also, will I add some box-shadow of #00FFA8 color?

2022-10-06 17:45 UTC, zugzwang03 commented
@anomic30 @Sneakad

2022-10-06 18:10 UTC, Sneakad approved these changes

2022-10-06 18:10 UTC, merged